name: Docker CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t gas-station-api .

      - name: Run Lint
        run: docker run gas-station-api npm run lint

      - name: Run Prettier Check
        run: docker run gas-station-api npx prettier --check .

      - name: Run Tests
        run: docker run gas-station-api npm test

      - name: Run Build
        run: docker run gas-station-api npm run build
